### ISSUE TITLE
Protocol - API Reference

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/livepeer-org#57]

**Comment by adamsoffer** [comment]
- [ ] Smart Contracts
- [ ] API
- [ ] Glossary

**Comment by wohlner** [comment]
API = subgraph

**Comment by yondonfu** [comment]
Feedback:

**index.md**

- Since staking pools aren't an in-protocol concept (although someone could certainly build a staking pool that then delegates on behalf of its members) I'm not sure that we should include the term in the overview description. Unless you are referring to another concept there?
- "Livepeer Subgraph" links to a [branch](https://github.com/livepeer/livepeerjs/tree/as/shares/packages/subgraph) instead of the master branch

**entities.md**

- Maybe we can add a note that the Transcoder entity contains data associated with the orchestrator role
- lastRoundLengthUpdateStartBlock -> Start block of round when round length was last updated
- Missing heading for WinningTicketRedeemedEvent
- Missing heading for DepositFundedEvent
- Missing heading for WithdrawalEvent
- Missing heading for SetCurrentRewardTokensEvent

**Comment by adamsoffer** [comment]
@yondonfu thanks. I just addressed this feedback here: https://github.com/livepeer/livepeer-org/commit/4153f60f0adf6110eb3343153f4a11cb04bd7dfb

**Comment by yondonfu** [comment]
Nice. API reference LGTM. Is Smart Contracts & Glossary still in scope for this issue? If so, we can keep this issue open, but if not, we can close it.

**Comment by adamsoffer** [comment]
Awesome! I think those are out of scope for this issue so we can close 👍
